version: '3.8'

services:
  postgresql:
    image: postgres:15.2
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres123
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      
volumes:
  postgresql_data: {}
