version: '3.8'

services:
  postgresql:
    container_name: postgresql-15.2
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres123
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  postgresql_data: {}
