version: '3.9'

services:
  postgres_db:
    container_name: spring-batch-process
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres123
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata: {}
